DOCS = vim_ami.txt vim_arch.txt vim_diff.txt vim_digr.txt vim_dos.txt \
	vim_help.txt vim_idx.txt vim_mac.txt vim_w32.txt vim_ref.txt \
	vim_tips.txt vim_unix.txt vim_win.txt vim_gui.txt vim_40.txt \
	vim_kcc.txt vim_rlh.txt vim_menu.txt

vim_tags: doctags $(DOCS)
	doctags $(DOCS) > tt
	sort <tt >vim_tags
	-delete tt

doctags: doctags.c
	cc doctags.c
	ln doctags.o -o doctags -lc

clean:
	-delete doctags vim_tags
