# The most simplistic Makefile for Win32 (NT and Windows 95)

ctags: ctags.exe

ctags.exe: ctags.c
# if using Microsoft Visual C++
	cl ctags.c -DWIN32 /link setargv.obj
# if using Borland C++
#	bcc32 -DWIN32 ctags.c c:\bc45\lib\32bit\wildargs.obj

clean:
	- del ctags.obj
	- del ctags.exe
