# The most simplistic Makefile for Win32 (NT and Windows 95)

xxd: xxd.exe

xxd.exe: xxd.c
# if using Microsoft Visual C++
     cl -DWIN32 xxd.c /link setargv.obj
# if using Borland C++
#    bcc32 -DWIN32 xxd.c c:\bc45\lib\32bit\wildargs.obj

clean:
     - del xxd.obj
     - del xxd.exe
