# The most simplistic Makefile for Win32 (Windows 95/NT)

SOURCES	= entry.c get.c main.c options.c parse.c read.c sort.c

ctags: ctags.exe

ctags.exe: $(SOURCES)
# if using Microsoft Visual C++
	cl -DWIN32 $(SOURCES) /Fectags.exe
# if using Borland C++
#	bcc32 -DWIN32 -O2 -w-par -w-pia -w-sus -ectags $(SOURCES)

clean:
	- del *.obj
	- del ctags.exe
