# $Id$
#
# Makefile for Win32 using Microsoft Visual C++ compiler

include source.mak

ctags: ctags.exe

ctags.exe: $(SOURCES) respw32
	cl -DWIN32 /Fe$@ @respw32

# Debug version
dctags.exe: $(SOURCES)
	cl -DWIN32 -DDEBUG /Fe$@ @respw32 debug.c

respw32:
	echo $(SOURCES) > $@

clean:
	- del *.obj
	- del ctags.exe
	- del dctags.exe
	- del respw32
	- del tags
