# The most simplistic Makefile, for DJGPP on MS-DOS

SOURCES	= entry.c get.c main.c options.c parse.c read.c sort.c
CFLAGS	= -O4 -Wall -DMSDOS

ctags.exe: $(SOURCES)
	gcc $(CFLAGS) -s -o ctags.exe $(SOURCES) -lpc

clean:
	del ctags.exe
