# Makefile for Win32 using Microsoft Visual C++ compiler

SOURCES	= args.c eiffel.c entry.c fortran.c get.c keyword.c main.c \
	options.c parse.c read.c sort.c strlist.c vstring.c

ctags: ctags.exe

ctags.exe: $(SOURCES) respw32
	cl -DWIN32 /Fe$@ @respw32

# Debug version
dctags.exe: $(SOURCES)
	cl -DWIN32 -DDEBUG /Fe$@ @respw32 debug.c

respw32:
	echo $(SOURCES) > $@

clean:
	- del *.obj
	- del ctags.exe
	- del dctags.exe
	- del respw32
	- del tags
