# $Id$
#
# Makefile for Exuberant Ctags under WIN32 with egcs/Mingw32 compiler
#
# Provided by Ron Aaron <v-ronaar@Exchange.Microsoft.com>

include source.mak

WINGW32 = ..
CFLAGS = -O4 -Wall -DWIN32 -I$(WINGW32)/lib -L$(WINGW32)/lib -s
CC = gcc $(CFLAGS) 

ctags: ctags.exe

ctags.exe: $(SOURCES)
	$(CC) -o ctags.exe $(SOURCES)
