# The most simplistic Makefile for Win32 (NT and Windows 95)

# Borland C library directory
BCLIBDIR = c:\bc45\lib\32bit

SOURCES	= entry.c get.c main.c options.c parse.c read.c sort.c

ctags: ctags.exe

ctags.exe: $(SOURCES)
# if using Microsoft Visual C++
	cl $(SOURCES) -DWIN32 /Za /Fectags.exe /link setargv.obj
# if using Borland C++
#	bcc32 -DWIN32 -A -w-pia -w-par -ectags $(SOURCES) $(BCLIBDIR)\wildargs.obj

clean:
	- del *.obj
	- del ctags.exe
