addcr <addcr.c >tmp
cp tmp addcr.c 
addcr <alloc.c >tmp
cp tmp alloc.c 
addcr <ascii.h >tmp
cp tmp ascii.h 
addcr <buffers.c >tmp
cp tmp buffers.c 
addcr <charset.c >tmp
cp tmp charset.c 
addcr <cmdline.c >tmp
cp tmp cmdline.c 
addcr <cmdtab.h >tmp
cp tmp cmdtab.h 
addcr <cmdtab.tab >tmp
cp tmp cmdtab.tab 
addcr <csearch.c >tmp
cp tmp csearch.c 
addcr <debug.h >tmp
cp tmp debug.h 
addcr <digraph.c >tmp
cp tmp digraph.c 
addcr <edit.c >tmp
cp tmp edit.c 
addcr <env.h >tmp
cp tmp env.h 
addcr <fileio.c >tmp
cp tmp fileio.c 
addcr <globals.h >tmp
cp tmp globals.h 
addcr <help.c >tmp
cp tmp help.c 
addcr <keymap.h >tmp
cp tmp keymap.h 
addcr <linefunc.c >tmp
cp tmp linefunc.c 
addcr <macros.h >tmp
cp tmp macros.h 
addcr <main.c >tmp
cp tmp main.c 
addcr <makefile >tmp
cp tmp makefile 
addcr <mark.c >tmp
cp tmp mark.c 
addcr <mark.h >tmp
cp tmp mark.h 
addcr <message.c >tmp
cp tmp message.c 
addcr <misccmds.c >tmp
cp tmp misccmds.c 
addcr <mkcmdtab.c >tmp
cp tmp mkcmdtab.c 
addcr <msdos.c >tmp
cp tmp msdos.c 
addcr <msdos.h >tmp
cp tmp msdos.h 
addcr <normal.c >tmp
cp tmp normal.c 
addcr <ops.c >tmp
cp tmp ops.c 
addcr <ops.h >tmp
cp tmp ops.h 
addcr <param.c >tmp
cp tmp param.c 
addcr <param.h >tmp
cp tmp param.h 
addcr <proto.h >tmp
cp tmp proto.h 
addcr <quickfix.c >tmp
cp tmp quickfix.c 
addcr <regexp.c >tmp
cp tmp regexp.c 
addcr <regexp.h >tmp
cp tmp regexp.h 
addcr <regmagic.h >tmp
cp tmp regmagic.h 
addcr <regsub.c >tmp
cp tmp regsub.c 
addcr <screen.c >tmp
cp tmp screen.c 
addcr <script.c >tmp
cp tmp script.c 
addcr <search.c >tmp
cp tmp search.c 
addcr <storage.c >tmp
cp tmp storage.c 
addcr <tag.c >tmp
cp tmp tag.c 
addcr <tags >tmp
cp tmp tags 
addcr <term.c >tmp
cp tmp term.c 
addcr <term.h >tmp
cp tmp term.h 
addcr <termlib.c >tmp
cp tmp termlib.c 
addcr <termlib.fix >tmp
cp tmp termlib.fix 
addcr <undo.c >tmp
cp tmp undo.c 
addcr <version.c >tmp
cp tmp version.c 
addcr <vim.h >tmp
cp tmp vim.h 
addcr <vim.prj >tmp
cp tmp vim.prj 
addcr <vimresp >tmp
cp tmp vimresp 
addcr <proto\alloc.pro >tmp
cp tmp proto\alloc.pro 
addcr <proto\amiga.pro >tmp
cp tmp proto\amiga.pro 
addcr <proto\buffers.pro >tmp
cp tmp proto\buffers.pro 
addcr <proto\charset.pro >tmp
cp tmp proto\charset.pro 
addcr <proto\cmdline.pro >tmp
cp tmp proto\cmdline.pro 
addcr <proto\csearch.pro >tmp
cp tmp proto\csearch.pro 
addcr <proto\digraph.pro >tmp
cp tmp proto\digraph.pro 
addcr <proto\edit.pro >tmp
cp tmp proto\edit.pro 
addcr <proto\fileio.pro >tmp
cp tmp proto\fileio.pro 
addcr <proto\help.pro >tmp
cp tmp proto\help.pro 
addcr <proto\linefunc.pro >tmp
cp tmp proto\linefunc.pro 
addcr <proto\main.pro >tmp
cp tmp proto\main.pro 
addcr <proto\mark.pro >tmp
cp tmp proto\mark.pro 
addcr <proto\message.pro >tmp
cp tmp proto\message.pro 
addcr <proto\misccmds.pro >tmp
cp tmp proto\misccmds.pro 
addcr <proto\normal.pro >tmp
cp tmp proto\normal.pro 
addcr <proto\ops.pro >tmp
cp tmp proto\ops.pro 
addcr <proto\param.pro >tmp
cp tmp proto\param.pro 
addcr <proto\quickfix.pro >tmp
cp tmp proto\quickfix.pro 
addcr <proto\regexp.pro >tmp
cp tmp proto\regexp.pro 
addcr <proto\regsub.pro >tmp
cp tmp proto\regsub.pro 
addcr <proto\screen.pro >tmp
cp tmp proto\screen.pro 
addcr <proto\script.pro >tmp
cp tmp proto\script.pro 
addcr <proto\search.pro >tmp
cp tmp proto\search.pro 
addcr <proto\storage.pro >tmp
cp tmp proto\storage.pro 
addcr <proto\tag.pro >tmp
cp tmp proto\tag.pro 
addcr <proto\term.pro >tmp
cp tmp proto\term.pro 
addcr <proto\termlib.pro >tmp
cp tmp proto\termlib.pro 
addcr <proto\undo.pro >tmp
cp tmp proto\undo.pro 
del tmp
