addcr <addcr.c >tmp
copy tmp addcr.c 
addcr <alloc.c >tmp
copy tmp alloc.c 
addcr <ascii.h >tmp
copy tmp ascii.h 
addcr <buffer.c >tmp
copy tmp buffer.c 
addcr <charset.c >tmp
copy tmp charset.c 
addcr <cmdcmds.c >tmp
copy tmp cmdcmds.c 
addcr <cmdline.c >tmp
copy tmp cmdline.c 
addcr <cmdtab.h >tmp
copy tmp cmdtab.h 
addcr <cmdtab.tab >tmp
copy tmp cmdtab.tab 
addcr <csearch.c >tmp
copy tmp csearch.c 
addcr <digraph.c >tmp
copy tmp digraph.c 
addcr <edit.c >tmp
copy tmp edit.c 
addcr <env.h >tmp
copy tmp env.h 
addcr <feature.h >tmp
copy tmp feature.h 
addcr <fileio.c >tmp
copy tmp fileio.c 
addcr <getchar.c >tmp
copy tmp getchar.c 
addcr <globals.h >tmp
copy tmp globals.h 
addcr <gui.c >tmp
copy tmp gui.c 
addcr <gui.h >tmp
copy tmp gui.h 
addcr <gui_moti.c >tmp
copy tmp gui_moti.c 
addcr <help.c >tmp
copy tmp help.c 
addcr <keymap.h >tmp
copy tmp keymap.h 
addcr <linefunc.c >tmp
copy tmp linefunc.c 
addcr <macros.h >tmp
copy tmp macros.h 
addcr <main.c >tmp
copy tmp main.c 
addcr <makefile >tmp
copy tmp makefile 
addcr <mark.c >tmp
copy tmp mark.c 
addcr <memfile.c >tmp
copy tmp memfile.c 
addcr <memline.c >tmp
copy tmp memline.c 
addcr <message.c >tmp
copy tmp message.c 
addcr <misccmds.c >tmp
copy tmp misccmds.c 
addcr <mkcmdtab.c >tmp
copy tmp mkcmdtab.c 
addcr <msdos.c >tmp
copy tmp msdos.c 
addcr <msdos.h >tmp
copy tmp msdos.h 
addcr <normal.c >tmp
copy tmp normal.c 
addcr <ops.c >tmp
copy tmp ops.c 
addcr <ops.h >tmp
copy tmp ops.h 
addcr <option.c >tmp
copy tmp option.c 
addcr <option.h >tmp
copy tmp option.h 
addcr <pathdef.c >tmp
copy tmp pathdef.c 
addcr <proto.h >tmp
copy tmp proto.h 
addcr <quickfix.c >tmp
copy tmp quickfix.c 
addcr <regexp.c >tmp
copy tmp regexp.c 
addcr <regexp.h >tmp
copy tmp regexp.h 
addcr <regmagic.h >tmp
copy tmp regmagic.h 
addcr <regsub.c >tmp
copy tmp regsub.c 
addcr <screen.c >tmp
copy tmp screen.c 
addcr <search.c >tmp
copy tmp search.c 
addcr <structs.h >tmp
copy tmp structs.h 
addcr <tables.c >tmp
copy tmp tables.c 
addcr <tag.c >tmp
copy tmp tag.c 
addcr <tags >tmp
copy tmp tags 
addcr <term.c >tmp
copy tmp term.c 
addcr <term.h >tmp
copy tmp term.h 
addcr <termlib.c >tmp
copy tmp termlib.c 
addcr <undo.c >tmp
copy tmp undo.c 
addcr <version.c >tmp
copy tmp version.c 
addcr <vim.h >tmp
copy tmp vim.h 
addcr <window.c >tmp
copy tmp window.c 
addcr <vim.prj >tmp
copy tmp vim.prj 
addcr <vimresp >tmp
copy tmp vimresp 
addcr <proto\alloc.pro >tmp
copy tmp proto\alloc.pro 
addcr <proto\amiga.pro >tmp
copy tmp proto\amiga.pro 
addcr <proto\buffers.pro >tmp
copy tmp proto\buffers.pro 
addcr <proto\charset.pro >tmp
copy tmp proto\charset.pro 
addcr <proto\cmdline.pro >tmp
copy tmp proto\cmdline.pro 
addcr <proto\csearch.pro >tmp
copy tmp proto\csearch.pro 
addcr <proto\digraph.pro >tmp
copy tmp proto\digraph.pro 
addcr <proto\edit.pro >tmp
copy tmp proto\edit.pro 
addcr <proto\fileio.pro >tmp
copy tmp proto\fileio.pro 
addcr <proto\help.pro >tmp
copy tmp proto\help.pro 
addcr <proto\linefunc.pro >tmp
copy tmp proto\linefunc.pro 
addcr <proto\main.pro >tmp
copy tmp proto\main.pro 
addcr <proto\mark.pro >tmp
copy tmp proto\mark.pro 
addcr <proto\message.pro >tmp
copy tmp proto\message.pro 
addcr <proto\misccmds.pro >tmp
copy tmp proto\misccmds.pro 
addcr <proto\normal.pro >tmp
copy tmp proto\normal.pro 
addcr <proto\ops.pro >tmp
copy tmp proto\ops.pro 
addcr <proto\param.pro >tmp
copy tmp proto\param.pro 
addcr <proto\quickfix.pro >tmp
copy tmp proto\quickfix.pro 
addcr <proto\regexp.pro >tmp
copy tmp proto\regexp.pro 
addcr <proto\regsub.pro >tmp
copy tmp proto\regsub.pro 
addcr <proto\screen.pro >tmp
copy tmp proto\screen.pro 
addcr <proto\script.pro >tmp
copy tmp proto\script.pro 
addcr <proto\search.pro >tmp
copy tmp proto\search.pro 
addcr <proto\storage.pro >tmp
copy tmp proto\storage.pro 
addcr <proto\tables.pro >tmp
copy tmp proto\tables.pro 
addcr <proto\tag.pro >tmp
copy tmp proto\tag.pro 
addcr <proto\term.pro >tmp
copy tmp proto\term.pro 
addcr <proto\termlib.pro >tmp
copy tmp proto\termlib.pro 
addcr <proto\undo.pro >tmp
copy tmp proto\undo.pro 
del tmp
